# Generated by tools/generate_cask.rb. Edit reviewed source inputs, then regenerate.
# Unofficial integration. Not maintained or endorsed by Moonshine or Universal Blue.
require "rbconfig"
cask "moonshine" do
  version "0.16.1"
  sha256 "9540ae5b88828bb3b8c442eb4794644aceb66fa4b623afc65ea0f29146fae267"
  url "https://github.com/hgaiser/moonshine/releases/download/v#{version}/moonshine-0.16.1-1.x86_64.rpm"
  name "Moonshine (unofficial Homebrew integration)"
  desc "Streaming server with locally labeled Fedora Atomic host integration"
  homepage "https://github.com/hgaiser/moonshine"
  conflicts_with cask: ["moonshine@0.16.1", "moonshine@0.16.0"]
  depends_on :linux
  depends_on arch: :x86_64
  depends_on formula: ["libarchive", "erofs-utils"]
  container type: :naked

  generated_script "moonshine-host.rb", content: <<~'MOONSHINE_RUBY'
    #!/usr/bin/env ruby
    require 'json'
    require 'digest'
    require 'pathname'
    require 'fileutils'
    require 'tmpdir'
    require 'open3'
    require 'shellwords'
    require 'set'
    require 'etc'
    require 'optparse'
    require 'rbconfig'

    module MoonshineHost
      extend self
      RELEASE = {'version'=>'0.16.1', 'sha256'=>'9540ae5b88828bb3b8c442eb4794644aceb66fa4b623afc65ea0f29146fae267', 'filename'=>'moonshine-0.16.1-1.x86_64.rpm'}.freeze
      IMAGE_NAME = 'moonshine-homebrew'
      STATE_DIR = Pathname('/var/lib/moonshine-homebrew')
      IMAGE_PATH = Pathname('/var/lib/extensions/moonshine-homebrew.raw')
      POLICY = Pathname('/etc/selinux/targeted/contexts/files/file_contexts')
      SAFE_PATH = '/usr/sbin:/usr/bin:/sbin:/bin'
      MAX_PACKAGE = 128 * 1024 * 1024
      PAYLOAD = {'/usr/bin/moonshine'=>0755, '/usr/bin/start-moonshine.sh'=>0755,
        '/usr/lib/moonshine/vulkan-layers/libmoonshine_wsi.so'=>0755,
        '/usr/share/vulkan/implicit_layer.d/VkLayer_moonshine_wsi.json'=>0644,
        '/usr/share/licenses/moonshine/LICENSE'=>0644}.freeze
      HOST_FILES = {'/usr/lib/systemd/system/moonshine@.service'=>'/etc/systemd/system/moonshine@.service',
        '/usr/lib/sysusers.d/moonshine.conf'=>'/etc/sysusers.d/moonshine.conf',
        '/usr/lib/modules-load.d/moonshine.conf'=>'/etc/modules-load.d/moonshine.conf',
        '/usr/lib/udev/rules.d/60-moonshine.rules'=>'/etc/udev/rules.d/60-moonshine.rules',
        '/usr/share/polkit-1/rules.d/50-moonshine-inhibit-sleep.rules'=>'/etc/polkit-1/rules.d/50-moonshine-inhibit-sleep.rules'}.freeze
      DROPIN = '/etc/systemd/system/moonshine@.service.d/10-homebrew-sysext.conf'
      DROPIN_CONTENT = "[Unit]\nRequires=systemd-sysext.service\nAfter=systemd-sysext.service\n"
      # Embed reviewed scriptlets so installed hooks do not read references from the tap.
      REVIEWED_SCRIPTS = {
        'postinstall' => <<~'POSTINSTALL'.chomp,
          #!/bin/sh
          # Post-install script for nfpm-generated packages (.deb/.rpm/.pkg.tar.zst).
          # Runs as root at package install time.

          # Reload udev rules and apply them to already-present devices.
          udevadm control --reload || true
          udevadm trigger || true

          # The 'moonshine' group used by the suspend-inhibit polkit rule
          # (dist/50-moonshine-inhibit-sleep.rules) is defined by the shipped sysusers.d
          # drop-in (dist/moonshine-sysusers.conf -> /usr/lib/sysusers.d/moonshine.conf).
          # Running systemd-sysusers applies that drop-in so the group exists immediately
          # instead of only after the next boot.
          systemd-sysusers 2>/dev/null || true

          # Load the virtual input modules now so no reboot is required
          # (dist/moonshine-modules.conf takes care of subsequent boots).
          modprobe uinput || true
          modprobe uhid || true

          echo "moonshine: enable for your user with:"
          echo "  sudo loginctl enable-linger <user>   # optional, for headless use"
          echo "  sudo systemctl enable --now moonshine@<user>"
        POSTINSTALL
        'postremove' => <<~'POSTREMOVE'.chomp
          #!/bin/sh
          # Post-remove script for nfpm-generated packages (.deb/.rpm/.pkg.tar.zst).

          # The udev rule was removed with the package; reload so it stops applying.
          udevadm control --reload || true
        POSTREMOVE
      }.freeze
      class Failure < StandardError; end
      Result = Struct.new(:stdout, :stderr, :returncode, keyword_init: true)
      def ensure!(condition, message)
        raise Failure, message unless condition
      end
      def digest(path)
        Digest::SHA256.file(path.to_s).hexdigest
      end
      def canonical_member(name)
        name = name.delete_prefix('./').sub(%r{/+\z}, '')
        relative = name.sub(%r{\A/+}, '')
        ensure!(!name.include?("\0") && !relative.split('/').include?('..'), 'Unsafe RPM payload path')
        path = Pathname('/' + relative).cleanpath.to_s
        ensure!(path == '/' + relative, 'Noncanonical RPM payload path')
        path
      end
      class Rpm
        attr_reader :path, :tags
        def initialize(path)
          @path = Pathname(path)
          MoonshineHost.ensure!(@path.file? && @path.size <= MAX_PACKAGE, 'RPM source must be a bounded regular file')
          @path.open('rb') do |io|
            lead = io.read(96)
            MoonshineHost.ensure!(lead && lead.bytesize == 96 && lead.byteslice(0,4) == "\xed\xab\xee\xdb".b, 'Not an RPM')
            self.class.header(io)
            io.seek((io.pos + 7) & ~7)
            @tags = self.class.header(io)
          end
        end
        def self.header(io)
          head = io.read(16)
          MoonshineHost.ensure!(head && head.bytesize == 16 && head.byteslice(0,4) == "\x8e\xad\xe8\x01".b, 'Invalid RPM header')
          count, size = head.byteslice(8,8).unpack('N2')
          MoonshineHost.ensure!(count <= 10_000 && size <= 16*1024*1024, 'RPM header exceeds limits')
          index, data = io.read(count*16), io.read(size)
          MoonshineHost.ensure!(index && data && index.bytesize == count*16 && data.bytesize == size, 'Truncated RPM header')
          tags, values, bytes = {}, 0, 0
          index.unpack('N*').each_slice(4) do |tag, kind, offset, length|
            MoonshineHost.ensure!((1..9).include?(kind), 'Unsupported RPM tag type')
            MoonshineHost.ensure!(offset <= size && length <= 100_000, 'Invalid RPM tag bounds')
            MoonshineHost.ensure!(!tags.key?(tag), 'Duplicate RPM tag')
            values += [6,7].include?(kind) ? 1 : length
            MoonshineHost.ensure!(values <= 100_000, 'RPM decoded values exceed aggregate limit')
            if [6,8,9].include?(kind)
              strings, cursor = [], offset
              (kind == 6 ? 1 : length).times do
                last = data.index("\0".b, cursor)
                MoonshineHost.ensure!(last && last >= cursor, 'Unterminated RPM string')
                bytes += last-cursor+1
                MoonshineHost.ensure!(bytes <= 32*1024*1024, 'RPM decoded bytes exceed aggregate limit')
                string = data.byteslice(cursor,last-cursor).force_encoding(Encoding::UTF_8)
                MoonshineHost.ensure!(string.valid_encoding?, 'Invalid RPM UTF-8 string')
                strings << string
                cursor = last+1
              end
              tags[tag] = kind == 6 ? strings.first : strings
            elsif [1,2,3,4,5].include?(kind)
              width, code = {1=>[1,'C*'],2=>[1,'C*'],3=>[2,'n*'],4=>[4,'N*'],5=>[8,'Q>*']}.fetch(kind)
              MoonshineHost.ensure!(offset+width*length <= size, 'Truncated RPM integer array')
              bytes += width*length
              MoonshineHost.ensure!(bytes <= 32*1024*1024, 'RPM decoded bytes exceed aggregate limit')
              tags[tag] = data.byteslice(offset,width*length).unpack(code)
            elsif kind == 7
              MoonshineHost.ensure!(offset+length <= size, 'Truncated RPM binary tag')
              bytes += length
              MoonshineHost.ensure!(bytes <= 32*1024*1024, 'RPM decoded bytes exceed aggregate limit')
              tags[tag] = data.byteslice(offset,length)
            end
          end
          tags
        end
        def inventory
          t = tags
          names = t[1027]
          unless names
            bases, dirs, indexes = t.fetch(1117,[]), t.fetch(1118,[]), t.fetch(1116,[])
            MoonshineHost.ensure!(bases.length == indexes.length && indexes.all? { |i| i < dirs.length }, 'Invalid RPM filename arrays or directory index')
            names = bases.zip(indexes).map { |base,i| dirs[i]+base }
          end
          modes, links = t.fetch(1030,[]), t.fetch(1036,[])
          MoonshineHost.ensure!(names.length == modes.length && modes.length == links.length, 'Malformed RPM file inventory')
          names.zip(modes,links).each_with_object({}) do |(name,mode,link), result|
            key = MoonshineHost.canonical_member(name)
            MoonshineHost.ensure!(!result.key?(key), 'Duplicate RPM payload path')
            MoonshineHost.ensure!(link.empty? && [0100000,0040000].include?(mode & 0170000), 'RPM contains a link or special file')
            MoonshineHost.ensure!((mode & 07000).zero?, 'RPM contains special permission bits')
            result[key] = mode
          end
        end
        def validate(release: RELEASE)
          MoonshineHost.ensure!(MoonshineHost.digest(path) == release['sha256'], 'Official RPM SHA-256 mismatch')
          MoonshineHost.ensure!([tags[1000],tags[1001],tags[1002],tags[1022]] == ['moonshine',release['version'],'1','x86_64'], 'Unexpected RPM identity')
          expected = (PAYLOAD.keys + HOST_FILES.keys).to_set
          files = inventory
          regular = files.select { |_,m| (m & 0170000) == 0100000 }.keys.to_set
          MoonshineHost.ensure!(regular == expected, 'RPM inventory changed; maintainer review required')
          parents = expected.flat_map { |p| Pathname(p).ascend.to_a.drop(1).map(&:to_s) }.to_set
          MoonshineHost.ensure!(files.all? { |p,m| (m & 0170000) == 0100000 || parents.include?(p) }, 'RPM contains an unexpected directory')
          [[1024,1086,'postinstall'],[1026,1088,'postremove']].each do |tag,prog,name|
            MoonshineHost.ensure!(tags.fetch(tag,'').sub(/\n+\z/,'') == REVIEWED_SCRIPTS[name], 'RPM scriptlet changed; review required')
            MoonshineHost.ensure!(['/bin/sh',['/bin/sh']].include?(tags[prog]), 'Unreviewed RPM scriptlet interpreter/arguments')
          end
          MoonshineHost.ensure!(!tags[1023] || tags[1023].empty?, 'Unexpected RPM pre-install scriptlet')
          MoonshineHost.ensure!(!tags[1025] || tags[1025].empty?, 'Unexpected RPM pre-remove scriptlet')
          files
        end
        def dependencies
          names, flags, versions = [1049,1048,1050].map { |t| tags.fetch(t,[]) }
          MoonshineHost.ensure!(names.length == flags.length && flags.length == versions.length, 'Malformed RPM requirements')
          names.zip(flags,versions).filter_map do |name,flag,version|
            next if name.start_with?('rpmlib(')
            op = {0=>'',2=>'<',4=>'>',8=>'=',10=>'<=',12=>'>='}[flag & 14]
            MoonshineHost.ensure!(!op.nil?, 'Unsupported RPM dependency operator')
            op.empty? ? name : "#{name} #{op} #{version}".strip
          end
        end
      end
      def command(args, check: true, output: nil)
        env = {'PATH'=>SAFE_PATH,'LC_ALL'=>'C','LANG'=>'C','HOME'=>'/root'}
        argv = args.map(&:to_s)
        if output
          _stdin, err, status = Open3.capture3(env, *argv, out: output, unsetenv_others: true)
          result = Result.new(stdout: '', stderr: err, returncode: status.exitstatus)
        else
          out, err, status = Open3.capture3(env, *argv, unsetenv_others: true)
          result = Result.new(stdout: out, stderr: err, returncode: status.exitstatus)
        end
        ensure!(!check || result.returncode == 0, "#{argv.first} exited #{result.returncode}: #{result.stderr.strip}")
        result
      end
      def tool(name)
        path = SAFE_PATH.split(':').map { |dir| File.join(dir,name) }.find { |p| File.file?(p) && File.executable?(p) }
        ensure!(path, "Missing host prerequisite: #{name}. No RPMs were layered.")
        path
      end
      def resolve_build_tools(paths={})
        names = ['bsdtar','mkfs.erofs','fsck.erofs']
        ensure!((paths.keys-names).empty?, 'Unknown conversion tool path override')
        names.to_h do |name|
          candidate = Pathname(paths.fetch(name) { tool(name) })
          ensure!(candidate.absolute? && candidate.basename.to_s == name, "Invalid conversion tool path for #{name}: #{candidate}")
          begin
            resolved = candidate.realpath
            info = resolved.stat
          rescue SystemCallError => e
            raise Failure, "Unavailable conversion tool #{name}: #{candidate}: #{e.message}"
          end
          ensure!(info.file? && resolved.executable? && (info.mode & 07022).zero?, "Unsafe conversion tool type/permissions: #{resolved}")
          [name,resolved.to_s]
        end
      end
      def extract(rpm, inventory, target, bsdtar: nil)
        bsdtar ||= tool('bsdtar')
        members = {}
        command([bsdtar,'-tf',rpm]).stdout.lines(chomp: true).each do |raw|
          key = canonical_member(raw)
          ensure!(!members.key?(key), 'Duplicate archive member')
          members[key] = raw
        end
        ensure!(members.keys.to_set == inventory.keys.to_set, 'RPM archive/header inventories differ')
        inventory.each do |path,mode|
          next unless (mode & 0170000) == 0100000
          dest = Pathname(target) / path.delete_prefix('/')
          dest.dirname.mkpath
          # Stream tar output into an exclusive regular file. Do not let tar create paths.
          dest.open(File::WRONLY | File::CREAT | File::EXCL,0600) do |output|
            argv = [bsdtar,'-xOf',rpm.to_s,'--',members.fetch(path)]
            err_read, err_write = IO.pipe
            begin
              pid = Process.spawn({'PATH'=>SAFE_PATH,'LC_ALL'=>'C','LANG'=>'C','HOME'=>'/root'}, *argv, out: output, err: err_write, unsetenv_others: true)
              err_write.close
              stderr = err_read.read
              _, status = Process.wait2(pid)
              ensure!(status.success?, "#{bsdtar} exited #{status.exitstatus}: #{stderr.strip}")
            ensure
              err_read.close unless err_read.closed?
              err_write.close unless err_write.closed?
            end
          end
          ensure!(dest.size <= 256*1024*1024, 'Extracted file exceeds limit')
          dest.chmod(PAYLOAD.fetch(path,0644))
        end
      end
      def os_release(path='/etc/os-release')
        File.readlines(path,chomp: true).each_with_object({}) do |line,result|
          next if line.empty? || line.start_with?('#')
          key,value = line.split('=',2)
          ensure!(value && key.match?(/\A[A-Z_]+\z/), 'Malformed os-release')
          words = Shellwords.split(value)
          ensure!(words.length == 1, 'Malformed os-release value')
          result[key] = words.first
        end
      end
      def validate_host(release,platform: RUBY_PLATFORM,boot_marker: Pathname('/run/ostree-booted'))
        ensure!(platform.start_with?('x86_64-linux'), 'Host eligibility requires Linux x86_64')
        id = release['ID']
        ensure!(id.is_a?(String) && id.match?(/\A[a-z0-9_.-]+\z/) && id != '_any', 'Host OS ID must be a non-wildcard os-release identifier')
        ancestry = [id, *release.fetch('ID_LIKE','').split]
        # Exclude enterprise derivatives even when they declare Fedora ancestry.
        ensure!(ancestry.include?('fedora') && (ancestry & %w[centos rhel rocky almalinux ol]).empty?, 'Only Fedora-based Atomic x86_64 hosts are eligible; CentOS/RHEL derivatives are excluded')
        ensure!(boot_marker.file? && !boot_marker.symlink?, 'An OSTree-booted Atomic host is required (/run/ostree-booted); installed bootc/rpm-ostree tools alone are insufficient')
        release
      end
      def extension_metadata(release)
        fields = {'ID'=>release.fetch('ID'),'ARCHITECTURE'=>'x86-64','SYSEXT_SCOPE'=>'system'}
        ensure!(fields['ID'] != '_any', 'Wildcard host OS identity is not permitted')
        key = release['SYSEXT_LEVEL'] ? 'SYSEXT_LEVEL' : 'VERSION_ID'
        ensure!(release[key], 'Host lacks extension compatibility version')
        fields[key] = release[key]
        ensure!(fields.values.all? { |v| v.match?(/\A[A-Za-z0-9_.-]+\z/) }, 'Unsafe extension compatibility metadata')
        fields.map { |k,v| "#{k}=#{v}\n" }.join
      end
      def nodes(tree)
        tree = Pathname(tree)
        [tree, *tree.glob('**/*',File::FNM_DOTMATCH).reject { |p| ['.','..'].include?(p.basename.to_s) }]
      end
      def context(path)
        ensure!(RUBY_PLATFORM.include?('linux'), 'SELinux contexts require Linux')
        require 'fiddle/import'
        unless defined?(MoonshineHost::Xattr)
          MoonshineHost.const_set(:Xattr,Module.new do
            extend Fiddle::Importer
            dlload Fiddle.dlopen(nil)
            extern 'long getxattr(const char*, const char*, void*, unsigned long)'
          end)
        end
        buffer = Fiddle::Pointer.malloc(32_768)
        size = Xattr.getxattr(path.to_s,'security.selinux',buffer,32_768)
        ensure!(size >= 0, "Cannot read SELinux context: #{path}: errno #{Fiddle.last_error}")
        buffer.to_s(size).delete_suffix("\0")
      end
      def label_tree(tree)
        command([tool('setfiles'),'-F','-r',tree,POLICY,tree])
        nodes(tree).to_h do |item|
          relative = item.relative_path_from(Pathname(tree)).to_s
          logical = relative == '.' ? '/' : '/' + relative
          expected = command([tool('matchpathcon'),'-n',logical]).stdout.strip
          actual = context(item)
          ensure!(actual == expected, "Incorrect staged SELinux context: #{logical} (expected #{expected}, got #{actual})")
          [relative,actual]
        end
      end
      def elf_requirements(path)
        header = command([tool('readelf'),'--file-header',path]).stdout
        ensure!(header.match?(/Class:\s+ELF64/) && header.match?(/Machine:\s+Advanced Micro Devices X86-64/), "Unsupported ELF architecture: #{path}")
        needed = command([tool('readelf'),'--dynamic',path]).stdout.scan(/\(NEEDED\).*\[([^\]]+)\]/).flatten
        info = command([tool('readelf'),'--version-info',path]).stdout.partition('Version needs section').last
        required, current = {}, nil
        info.each_line do |line|
          current = Regexp.last_match(1) if line =~ /File: (\S+)/
          if line =~ /Name: (\S+)/ && current
            (required[current] ||= Set.new) << Regexp.last_match(1)
          end
        end
        [needed,required]
      end
      def verify_elf(tree)
        libraries = {}
        command([tool('ldconfig'),'-p']).stdout.each_line do |line|
          if line =~ /\s*(\S+) \([^)]*x86-64[^)]*\) => (\S+)/
            libraries[Regexp.last_match(1)] ||= Pathname(Regexp.last_match(2))
          end
        end
        pending = [Pathname(tree)/'usr/bin/moonshine',Pathname(tree)/'usr/lib/moonshine/vulkan-layers/libmoonshine_wsi.so']
        seen = Set.new
        until pending.empty?
          binary = pending.pop
          next if seen.include?(binary)
          seen << binary
          needed, versions = elf_requirements(binary)
          needed.each do |name|
            ensure!(libraries.key?(name), "Missing host ELF library: #{name}")
            library = libraries[name]
            definitions = command([tool('readelf'),'--version-info',library]).stdout.partition('Version needs section').first
            provided = definitions.scan(/Name: (\S+)/).flatten.to_set
            ensure!(versions.fetch(name,Set.new).subset?(provided), "Host ELF symbol versions incompatible: #{name}")
            pending << library
          end
        end
      end
      def atomic_write(path,data,mode=0600)
        path = Pathname(path)
        path.dirname.mkpath
        temp = nil
        begin
          require 'tempfile'
          file = Tempfile.create(['.moonshine-',''],path.dirname.to_s)
          temp = file.path
          file.chmod(mode)
          file.binmode
          file.write(data)
          file.flush
          file.fsync
          file.close
          File.rename(temp,path)
          File.open(path.dirname,File::RDONLY) { |dir| dir.fsync }
        ensure
          file&.close unless file&.closed?
          File.unlink(temp) if temp && File.exist?(temp)
        end
      end
      def secure_path(path,allow_missing: false)
        Pathname(path).ascend do |part|
          unless part.exist? || part.symlink?
            ensure!(allow_missing, "Missing managed path: #{part}")
            next
          end
          info = part.lstat
          ensure!(!info.symlink? && info.uid == 0 && (info.mode & 0022).zero?, "Unsafe managed path ownership/type/permissions: #{part}")
        end
      end
      def extension_names(rows)
        ensure!(rows.is_a?(Array), 'Unsupported systemd-sysext status schema')
        rows.each_with_object(Set.new) do |row,names|
          ensure!(row.is_a?(Hash) && row.key?('extensions'), 'Unsupported sysext status row')
          values = row['extensions']
          next if values.nil? || values == 'none'
          ensure!(values.is_a?(Array) && values.all? { |name| name.is_a?(String) }, 'Unsupported sysext extensions schema')
          names.merge(values)
        end
      end
      def merged_names
        extension_names(JSON.parse(command([tool('systemd-sysext'),'status','--json=short']).stdout))
      end
      def mounted?(path)
        return false unless File.exist?(path)
        # Detect bind mounts even when they use the same device.
        command([tool('mountpoint'),'-q',path],check: false).returncode == 0
      end
      class Host
        include MoonshineHost
        attr_reader :root, :receipt, :build_tools
        def initialize(root=STATE_DIR,build_tools: {})
          @root, @build_tools = Pathname(root), build_tools.dup
          @receipt = @root/'state.json'
        end
        def locked
          ensure!(RUBY_PLATFORM.include?('linux') && Process.euid == 0, 'Host operations require Linux and sudo')
          secure_path(root,allow_missing: true)
          FileUtils.mkdir_p(root,mode: 0700)
          secure_path(root)
          File.open(root/'lock',File::CREAT | File::RDWR | File::NOFOLLOW,0600) do |lock|
            secure_path(root/'lock')
            lock.flock(File::LOCK_EX)
            yield
          end
        end
        def state
          return {'schema'=>1,'phase'=>'empty','active'=>nil,'recovery'=>nil,'services'=>{}} unless receipt.exist?
          secure_path(receipt)
          value = JSON.parse(receipt.read)
          ensure!(value['schema'] == 1 && %w[empty active removing removed installing].include?(value['phase']), 'Unsupported lifecycle state schema/phase')
          value
        end
        def save(value)
          atomic_write(receipt,JSON.pretty_generate(value)+"\n")
        end
        def bundle(name)
          ensure!(name.is_a?(String) && name.match?(/\Abundle-[a-z0-9_]+\z/), 'Invalid bundle identifier')
          path = root/name
          secure_path(path)
          secure_path(path/'manifest.json')
          manifest = JSON.parse((path/'manifest.json').read)
          ensure!(manifest.fetch('host_files').keys.to_set == (HOST_FILES.values+[DROPIN]).to_set && manifest.fetch('payload').keys.to_set == PAYLOAD.keys.to_set, 'Recovery bundle inventory differs from reviewed inventory')
          package = path/'release.rpm'
          secure_path(package)
          ensure!(digest(package) == manifest.fetch('release').fetch('sha256'), 'Retained official RPM checksum mismatch')
          cached = Rpm.new(package)
          ensure!([cached.tags[1000],cached.tags[1001],cached.tags[1022]] == ['moonshine',manifest['release']['version'],'x86_64'], 'Retained RPM identity mismatch')
          [[1024,1086,'postinstall'],[1026,1088,'postremove']].each do |tag,prog,hook|
            ensure!(cached.tags.fetch(tag,'').sub(/\n+\z/,'') == manifest['scriptlets'][hook] && ['/bin/sh',['/bin/sh']].include?(cached.tags[prog]), 'Retained scriptlet/header mismatch')
          end
          ensure!(digest(path/'image.raw') == manifest['image_sha256'], 'Recovery image checksum mismatch')
          manifest['host_files'].each { |dest,sha| ensure!(digest(path/'host'/dest.delete_prefix('/')) == sha, 'Recovery host-file checksum mismatch') }
          [path,manifest]
        end
        def prerequisites
          release = os_release
          validate_host(release)
          %w[rpm setfiles matchpathcon restorecon getenforce mount umount mountpoint systemd-sysext systemctl systemd-sysusers udevadm modprobe readelf ldconfig Xwayland].each { |n| tool(n) }
          ensure!(command([tool('getenforce')]).stdout.strip == 'Enforcing', 'SELinux must remain enforcing')
          ensure!(POLICY.file?, 'Missing targeted SELinux file-context policy')
          ensure!(command([tool('rpm'),'-q','moonshine'],check: false).returncode == 1, 'Conflicting Moonshine RPM or unreadable host RPM database')
          version = command([tool('systemd-sysext'),'--version']).stdout[/systemd (\d+)/,1]
          ensure!(version && version.to_i >= 257, 'systemd 257+ is required for the hierarchy-labeling fix')
          %w[/etc/extensions /run/extensions].each do |dir|
            ['', '.raw'].each do |suffix|
              path = Pathname(dir)/(IMAGE_NAME+suffix)
              ensure!(!path.exist? && !path.symlink?, "Extension is shadowed or masked: #{path}")
            end
          end
          release
        end
        def fingerprint
          release = os_release
          sha = Digest::SHA256.new
          POLICY.dirname.glob('file_contexts*').sort.each do |path|
            sha.update(path.basename.to_s+"\0").update(path.binread) if path.file?
          end
          loaded = Pathname('/sys/fs/selinux/policy')
          ensure!(loaded.file?, 'Cannot fingerprint the loaded SELinux policy')
          sha.update(loaded.binread)
          {'id'=>release['ID'],'version_id'=>release['VERSION_ID'],'sysext_level'=>release['SYSEXT_LEVEL'],'selinux_files_sha256'=>sha.hexdigest}
        end
        def refresh
          before = merged_names - [IMAGE_NAME]
          labels = %w[/usr /opt].select { |p| File.exist?(p) }.to_h { |p| [p,context(p)] }
          command([tool('systemd-sysext'),'refresh'])
          ensure!(before.subset?(merged_names), 'Refresh did not preserve all previously merged unrelated extensions')
          ensure!(labels.all? { |p,label| context(p) == label }, 'Refresh changed a base hierarchy SELinux context')
        end
        def valid_unit!(unit)
          ensure!(unit.match?(/\Amoonshine@[^\/\s*?\[\]]+\.service\z/), 'Invalid saved service instance')
        end
        def capture_services
          names = Set.new
          %w[list-units list-unit-files].each do |verb|
            command([tool('systemctl'),verb,'--all','--type=service','--no-legend','--plain','moonshine@*.service']).stdout.each_line do |line|
              unit = line.split.first
              names << unit if unit && unit.match?(/\Amoonshine@[^\/\s]+\.service\z/)
            end
          end
          names.sort.to_h do |unit|
            enabled = command([tool('systemctl'),'is-enabled',unit],check: false).stdout.strip
            fragment = command([tool('systemctl'),'show',unit,'--property=FragmentPath','--value']).stdout.strip
            ensure!(fragment == HOST_FILES['/usr/lib/systemd/system/moonshine@.service'] || (fragment == '/dev/null' && %w[masked masked-runtime].include?(enabled)), "Conflicting service instance: #{unit}")
            ensure!(%w[enabled enabled-runtime disabled static masked masked-runtime].include?(enabled), "Unsupported service enablement state: #{unit}: #{enabled}")
            active = command([tool('systemctl'),'is-active',unit],check: false).stdout.strip
            ensure!(%w[active inactive failed].include?(active), "Service is transitioning: #{unit}: #{active}")
            ensure!(!(active == 'active' && %w[masked masked-runtime].include?(enabled)), "Cannot restart a masked running instance safely: #{unit}")
            [unit,{'enabled'=>enabled,'running'=>active == 'active'}]
          end
        end
        def restore_services(snapshot)
          snapshot.each do |unit,value|
            valid_unit!(unit)
            if %w[enabled enabled-runtime].include?(value['enabled'])
              args = [tool('systemctl'),'enable']
              args << '--runtime' if value['enabled'] == 'enabled-runtime'
              command(args+[unit])
            end
            if value['running']
              command([tool('systemctl'),'start',unit])
              ensure!(command([tool('systemctl'),'is-active',unit],check: false).stdout.strip == 'active', "Service did not become active: #{unit}")
            end
          end
        end
        def stop_services(snapshot)
          snapshot.each_key do |unit|
            valid_unit!(unit)
            next if command([tool('systemctl'),'show',unit,'--property=LoadState','--value']).stdout.strip == 'not-found'
            enabled = command([tool('systemctl'),'is-enabled',unit],check: false).stdout.strip
            fragment = command([tool('systemctl'),'show',unit,'--property=FragmentPath','--value']).stdout.strip
            ensure!(fragment == HOST_FILES['/usr/lib/systemd/system/moonshine@.service'] || (fragment == '/dev/null' && %w[masked masked-runtime].include?(enabled)), "Service ownership changed during cleanup: #{unit}")
            command([tool('systemctl'),'stop',unit])
            if %w[enabled enabled-runtime].include?(enabled)
              args = [tool('systemctl'),'disable']
              args << '--runtime' if enabled == 'enabled-runtime'
              command(args+[unit])
            end
          end
        end
        def reset_removed_services(snapshot)
          snapshot.each do |unit, saved|
            valid_unit!(unit)
            observed = command([tool('systemctl'),'show',unit,'--property=LoadState,ActiveState,FragmentPath','--all'],check: false)
            rows = observed.stdout.lines.map { |line| line.chomp.split('=',2) }
            ensure!(rows.size == 3 && rows.all? { |row| row.size == 2 } && rows.map(&:first).sort == %w[ActiveState FragmentPath LoadState], "Cannot inspect removed service: #{unit}")
            properties = rows.to_h
            missing = properties['LoadState'] == 'not-found' && properties['FragmentPath'].empty?
            masked = properties['LoadState'] == 'masked' && properties['FragmentPath'] == '/dev/null' && %w[masked masked-runtime].include?(saved['enabled'])
            ensure!(observed.returncode == 0, "Cannot inspect removed service: #{unit}")
            ensure!(missing || masked, "Service ownership changed after removal: #{unit}")
            ensure!(%w[inactive failed].include?(properties['ActiveState']), "Removed service is not stopped: #{unit}")
            command([tool('systemctl'),'reset-failed',unit]) if properties['ActiveState'] == 'failed'
          end
        end
        def check_owned(manifest)
          manifest['host_files'].merge(IMAGE_PATH.to_s=>manifest['image_sha256']).each do |dest,sha|
            path = Pathname(dest)
            secure_path(path,allow_missing: true)
            ensure!(!path.exist? || (path.file? && digest(path) == sha), "Owned file was changed externally: #{path}")
          end
        end
        def uninstall
          value = state
          unless value['active']
            ensure!(!IMAGE_PATH.exist? && !IMAGE_PATH.symlink?, 'Untracked active image; refusing cleanup')
            return
          end
          _, manifest = bundle(value['active'])
          check_owned(manifest)
          if value['phase'] == 'active'
            value['services'] = capture_services
            value['recovery'] = value['active']
          end
          value['phase'] = 'removing'
          save(value)
          stop_services(value['services'])
          manifest['host_files'].each_key { |dest| File.unlink(dest) if File.exist?(dest) }
          IMAGE_PATH.unlink if IMAGE_PATH.exist?
          refresh
          command([tool('systemctl'),'daemon-reload'])
          scriptlet(manifest,'postremove',0)
          command([tool('udevadm'),'control','--reload'])
          reset_removed_services(value['services'])
          value.merge!('active'=>nil,'phase'=>'removed')
          save(value)
        end
        def scriptlet(manifest,name,argument)
          command(['/bin/sh','-c',manifest['scriptlets'].fetch(name),"moonshine-#{name}",argument.to_s])
        end
        def build(source)
          tools = resolve_build_tools(build_tools)
          # Keep bundle names compatible with retained lifecycle journals.
          path = root/('bundle-'+Random.urandom(12).unpack1('H*'))
          path.mkdir(0700)
          begin
            package = path/'release.rpm'
            File.open(source,'rb') do |src|
              ensure!(src.stat.file? && src.stat.size <= MAX_PACKAGE, 'RPM source must be a bounded regular file')
              package.open(File::WRONLY|File::CREAT|File::EXCL,0600) do |dst|
                total = 0
                while (chunk = src.read(1024*1024))
                  total += chunk.bytesize
                  ensure!(total <= MAX_PACKAGE, 'RPM changed size during staging')
                  dst.write(chunk)
                end
              end
            end
            ensure!(digest(package) == RELEASE['sha256'], 'Official RPM SHA-256 mismatch')
            rpm = Rpm.new(package)
            inventory = rpm.validate
            rpm.dependencies.each { |dep| ensure!(command([tool('rpm'),'-q','--whatprovides',dep],check: false).returncode == 0, "Missing host RPM prerequisite: #{dep}. No packages were layered.") }
            tree = path/'extracted'
            tree.mkdir
            extract(package,inventory,tree,bsdtar: tools['bsdtar'])
            verify_elf(tree)
            host = path/'host'
            HOST_FILES.each do |src,dest|
              target = host/dest.delete_prefix('/')
              target.dirname.mkpath
              FileUtils.mv(tree/src.delete_prefix('/'),target)
            end
            target = host/DROPIN.delete_prefix('/')
            target.dirname.mkpath
            target.binwrite(DROPIN_CONTENT)
            target.chmod(0644)
            nodes(tree).reverse_each { |p| p.rmdir if p != tree && p.directory? && p.children.empty? }
            metadata = tree/'usr/lib/extension-release.d'/('extension-release.'+IMAGE_NAME)
            metadata.dirname.mkpath
            metadata.write(extension_metadata(os_release))
            metadata.chmod(0644)
            nodes(tree).each { |p| p.chown(0,0) }
            labels = label_tree(tree)
            image = path/'image.raw'
            command([tools['mkfs.erofs'],image,tree])
            command([tools['fsck.erofs'],image])
            view = path/'inspect'
            view.mkdir
            command([tool('mount'),'-t','erofs','-o','loop,ro',image,view])
            begin
              labels.each do |rel,label|
                item = view/rel
                ensure!(context(item) == label, "EROFS lost SELinux context: #{rel}")
                ensure!(item.stat.uid == 0 && item.stat.gid == 0, 'EROFS ownership changed')
              end
              PAYLOAD.each_key { |rel| ensure!(digest(view/rel.delete_prefix('/')) == digest(tree/rel.delete_prefix('/')), 'EROFS payload differs from staged payload') }
            ensure
              command([tool('umount'),view])
            end
            manifest = {'release'=>RELEASE,'host'=>fingerprint,'image_sha256'=>digest(image),'build_tools'=>tools,
              'host_files'=>(HOST_FILES.values+[DROPIN]).to_h { |dest| [dest,digest(host/dest.delete_prefix('/'))] },
              'payload'=>PAYLOAD.keys.to_h { |src| [src,digest(tree/src.delete_prefix('/'))] },
              'scriptlets'=>{'postinstall'=>rpm.tags[1024].sub(/\n+\z/,''),'postremove'=>rpm.tags[1026].sub(/\n+\z/,'')}}
            atomic_write(path/'manifest.json',JSON.pretty_generate(manifest)+"\n")
            FileUtils.remove_entry_secure(tree.to_s)
            view.rmdir
            path.basename.to_s
          rescue StandardError
            FileUtils.remove_entry_secure(path.to_s) unless mounted?(path/'inspect')
            raise
          end
        end
        def validate_cached_image(bundle,manifest)
          Rpm.new(bundle/'release.rpm').dependencies.each { |dep| ensure!(command([tool('rpm'),'-q','--whatprovides',dep],check: false).returncode == 0, "Missing retained-image prerequisite: #{dep}") }
          view = Pathname(Dir.mktmpdir('validate-',bundle.to_s))
          mounted = false
          begin
            command([tool('mount'),'-t','erofs','-o','loop,ro',bundle/'image.raw',view])
            mounted = true
            nodes(view).each do |item|
              relative = item.relative_path_from(view).to_s
              logical = relative == '.' ? '/' : '/' + relative
              expected = command([tool('matchpathcon'),'-n',logical]).stdout.strip
              ensure!(context(item) == expected, "Retained image context mismatch: #{logical}")
            end
            verify_elf(view)
            manifest['payload'].each { |logical,sha| ensure!(digest(view/logical.delete_prefix('/')) == sha, 'Retained image payload mismatch') }
          ensure
            command([tool('umount'),view]) if mounted
            view.rmdir unless mounted?(view)
          end
        end
        def activate(name)
          path, manifest = bundle(name)
          ensure!(manifest['host'] == fingerprint, 'Recovery image is incompatible with current host/policy; rebuild required')
          validate_cached_image(path,manifest)
          value = state
          ensure!(!value['active'], 'Remove owned active integration before activation')
          (manifest['host_files'].keys+[IMAGE_PATH.to_s]).each do |dest|
            target = Pathname(dest)
            secure_path(target,allow_missing: true)
            ensure!(!target.exist? && !target.symlink?, "Conflicting host file: #{target}")
          end
          PAYLOAD.each_key { |dest| ensure!(!File.exist?(dest) && !File.symlink?(dest), "Conflicting payload: #{dest}") }
          value.merge!('active'=>name,'phase'=>'installing')
          save(value)
          manifest['host_files'].each_key do |dest|
            atomic_write(dest,(path/'host'/dest.delete_prefix('/')).binread,0644)
            command([tool('restorecon'),'-F',dest])
          end
          atomic_write(IMAGE_PATH,(path/'image.raw').binread,0644)
          command([tool('restorecon'),'-F',IMAGE_PATH])
          refresh
          command([tool('systemctl'),'daemon-reload'])
          scriptlet(manifest,'postinstall',1)
          verify_setup(manifest)
          restore_services(value['services'])
          value['phase'] = 'active'
          save(value)
        end
        def verify_setup(manifest)
          ensure!(merged_names.include?(IMAGE_NAME) && IMAGE_PATH.file?, 'Moonshine extension did not merge')
          check_owned(manifest)
          manifest['payload'].each do |logical,sha|
            ensure!(File.file?(logical) && digest(logical) == sha, "Merged payload mismatch: #{logical}")
            ensure!(context(logical) == command([tool('matchpathcon'),'-n',logical]).stdout.strip, "Merged payload context mismatch: #{logical}")
          end
          manifest['host_files'].each_key { |dest| ensure!(command([tool('matchpathcon'),'-V',dest],check: false).returncode == 0, "Host file context mismatch: #{dest}") }
          begin
            Etc.getgrnam('moonshine')
          rescue ArgumentError
            raise Failure, 'RPM post-install did not create the moonshine group'
          end
          command([tool('udevadm'),'control','--reload'])
          command([tool('udevadm'),'trigger'])
          %w[uinput uhid].each { |mod| ensure!(File.exist?("/sys/module/#{mod}") && File.exist?("/dev/#{mod}"), "Input module/device unavailable: #{mod}") }
          ensure!(command([tool('getenforce')]).stdout.strip == 'Enforcing', 'SELinux no longer enforcing')
        end
        def recover
          value = state
          ensure!(value['recovery'], 'No retained installation is available')
          target = value['recovery']
          _, manifest = bundle(target)
          ensure!(manifest['host'] == fingerprint, 'Recovery image is incompatible with current host/policy; rebuild required')
          if value['active'] == target && value['phase'] == 'active'
            verify_setup(manifest)
            return
          end
          uninstall if value['active']
          activate(target)
        end
        def purge_recovery
          value = state
          ensure!(!value['active'] && %w[removed empty].include?(value['phase']), 'Uninstall before purging recovery material')
          ensure!(!IMAGE_PATH.exist? && !IMAGE_PATH.symlink? && !merged_names.include?(IMAGE_NAME), 'Active image still exists or is merged')
          bundles = root.glob('bundle-*')
          bundles.each do |dir|
            ensure!(dir.directory? && !dir.symlink?, 'Unsafe recovery directory')
            secure_path(dir)
            ensure!(!nodes(dir).any? { |p| mounted?(p) }, "Recovery inspection mount is still present: #{dir}")
          end
          bundles.each { |dir| FileUtils.remove_entry_secure(dir.to_s) }
          value.merge!('recovery'=>nil,'services'=>{})
          save(value)
        end
        def install(package)
          prerequisites
          value = state
          if value['active'] && value['phase'] == 'active'
            _, manifest = bundle(value['active'])
            if manifest['release'] == RELEASE && manifest['host'] == fingerprint
              verify_setup(manifest)
              return
            end
          end
          cached = [value['active'],value['recovery']].compact.find do |name|
            _, manifest = bundle(name)
            manifest['release'] == RELEASE && manifest['host'] == fingerprint
          end
          uninstall if value['active']
          previous = state['recovery']
          begin
            if cached
              activate(cached)
            else
              activate(build(package))
            end
          rescue StandardError => original
            begin
              uninstall if state['active']
              activate(previous) if previous
            rescue StandardError => recovery
              raise Failure, "Install failed: #{original.message}. Recovery also failed: #{recovery.message}. Retained state: #{receipt}"
            end
            raise Failure, "Install failed: #{original.message}. #{previous ? 'Previous installation restored.' : 'No previous installation existed.'}"
          end
        end
      end
      def main(argv=ARGV)
        options, tools = {}, {}
        parser = OptionParser.new do |p|
          p.banner = 'Usage: moonshine_host.rb ACTION [--rpm FILE] [--bsdtar PATH --mkfs-erofs PATH --fsck-erofs PATH]'
          p.on('--rpm FILE') { |v| options[:rpm] = v }
          %w[bsdtar mkfs.erofs fsck.erofs].each { |n| p.on('--'+n.tr('.','-')+' PATH') { |v| tools[n] = v } }
        end
        parser.parse!(argv)
        action = argv.shift
        ensure!(argv.empty? && %w[inspect install uninstall recover status prepare purge-recovery].include?(action), parser.to_s)
        ensure!(tools.empty? || %w[install prepare].include?(action), 'Conversion-tool paths are only valid for install or prepare')
        if action == 'inspect'
          ensure!(options[:rpm], 'inspect requires --rpm')
          ensure!(digest(options[:rpm]) == RELEASE['sha256'], 'Official RPM SHA-256 mismatch')
          rpm = Rpm.new(options[:rpm])
          puts JSON.pretty_generate('release'=>RELEASE,'inventory'=>rpm.validate,'dependencies'=>rpm.dependencies,'scriptlet_interpreters'=>{'postinstall'=>rpm.tags[1086],'postremove'=>rpm.tags[1088]})
          return 0
        end
        host = Host.new(build_tools: tools)
        if action == 'status'
          ensure!(!host.root.exist? || Process.euid == 0, 'Reading installed host state requires sudo')
          puts JSON.pretty_generate(host.state)
          return 0
        end
        host.locked do
          if %w[install prepare].include?(action)
            ensure!(options[:rpm], "#{action} requires --rpm")
            source = File.binread(__FILE__).sub(/\A#![^\n]*/, '#!'+File.realpath(RbConfig.ruby)+' --disable=rubyopt')
            atomic_write(host.root/'helper.rb',source,0700)
          end
          case action
          when 'install' then host.install(options[:rpm])
          when 'prepare' then host.prerequisites; puts(host.root/host.build(options[:rpm]))
          when 'uninstall' then host.uninstall
          when 'recover' then host.prerequisites; host.recover
          when 'purge-recovery' then host.purge_recovery
          end
        end
        0
      rescue Failure, SystemCallError, ArgumentError, KeyError, JSON::ParserError, OptionParser::ParseError => e
        warn "moonshine-homebrew: #{e.message}"
        1
      end
    end
    exit MoonshineHost.main if $PROGRAM_NAME == __FILE__
  MOONSHINE_RUBY

  generated_script "moonshine-token-guard.rb", content: <<~'MOONSHINE_GUARD'
    require 'open3'
    require 'optparse'
    require 'pathname'

    module MoonshineTokenGuard
      extend self
      TAP = 'evertonstz/moonshine-tap'
      class Failure < StandardError; end

      def conflicts(requested, installed)
        unless requested.match?(%r{\Aevertonstz/moonshine-tap/moonshine(?:@(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*))?\z})
          raise Failure, 'Invalid requested Moonshine cask token'
        end
        installed.reject do |name|
          raise Failure, 'Malformed installed-cask listing' unless name.match?(%r{\A[a-zA-Z0-9@._+/-]+\z})
          base = name.split('/').last
          name == requested || (base != 'moonshine' && !base.start_with?('moonshine@'))
        end
      end

      def run(brew)
        Open3.capture3({'RUBYOPT' => nil, 'RUBYLIB' => nil,
                       'HOMEBREW_NO_AUTO_UPDATE' => '1', 'HOMEBREW_NO_ANALYTICS' => '1'},
                      brew, 'list', '--cask', '--full-name', '-1')
      end

      def main(argv = ARGV, euid: Process.euid, runner: method(:run))
        options = {}
        parser = OptionParser.new do |p|
          p.banner = 'Usage: moonshine_token_guard.rb --brew FILE --token TAP/CASK'
          p.on('--brew FILE') { |value| options[:brew] = value }
          p.on('--token TOKEN') { |value| options[:token] = value }
        end
        parser.parse!(argv)
        raise Failure, parser.to_s unless argv.empty? && options.keys.sort == %i[brew token]
        raise Failure, 'Run Homebrew token checks as the normal operator, never with sudo' if euid.zero?
        brew = Pathname(options[:brew])
        raise Failure, 'Homebrew executable must be an absolute executable path' unless brew.absolute? && brew.file? && brew.executable?
        output, error, status = runner.call(brew.to_s)
        raise Failure, "Cannot list installed casks: #{error.strip}" unless status.success? && output.bytesize <= 1024 * 1024
        other = conflicts(options[:token], output.lines.map(&:strip).reject(&:empty?))
        unless other.empty?
          raise Failure, "Ordinarily uninstall #{other.join(', ')} before installing #{options[:token]}. Do not use --zap."
        end
        0
      rescue Failure, SystemCallError, OptionParser::ParseError => e
        warn "moonshine-token-guard: #{e.message}"
        1
      end
    end

    exit MoonshineTokenGuard.main if $PROGRAM_NAME == __FILE__
  MOONSHINE_GUARD

  postflight_steps do
    run RbConfig.ruby,
        args: ["--disable=rubyopt", "{{staged_path}}/moonshine-token-guard.rb", "--brew",
               "{{HOMEBREW_BREW_FILE}}", "--token", "evertonstz/moonshine-tap/moonshine"],
        print_stdout: true
    run RbConfig.ruby,
        args: ["--disable=rubyopt", "{{staged_path}}/moonshine-host.rb", "install", "--rpm",
               "{{staged_path}}/moonshine-0.16.1-1.x86_64.rpm",
               "--bsdtar", "{{HOMEBREW_PREFIX}}/opt/libarchive/bin/bsdtar",
               "--mkfs-erofs", "{{HOMEBREW_PREFIX}}/opt/erofs-utils/bin/mkfs.erofs",
               "--fsck-erofs", "{{HOMEBREW_PREFIX}}/opt/erofs-utils/bin/fsck.erofs"],
        sudo: true,
        print_stdout: true
  end
  uninstall_preflight_steps do
    run RbConfig.ruby,
        args: ["--disable=rubyopt", "{{staged_path}}/moonshine-host.rb", "uninstall"],
        sudo: true,
        print_stdout: true
  end
  caveats <<~EOS
    Unofficial; not endorsed by Moonshine or Universal Blue.
    Experimental Fedora Atomic x86_64 integration, including Fedora-based UBlue images.
    Requires an OSTree-booted host; CentOS/RHEL derivatives and ARM are excluded.
    Only Bazzite has lifecycle acceptance; other eligible images are untested.
    Consult README.md for tested limits and version-switching instructions.
    Only one Moonshine cask variant can be installed. Ordinarily uninstall before switching tokens.
    Upgrades interrupt streaming. Ordinary uninstall removes owned active integration.
    Pairing/configuration, groups, lingering, administrator files and unrelated extensions remain.
    Inactive recovery material is retained in /var/lib/moonshine-homebrew.
    Fresh installation does not enable Moonshine or lingering.
    Reinstall can restore retained enabled/running choices.
    Explicit account activation: sudo systemctl enable --now moonshine@<user>.service
    Explicit cached recovery: sudo /var/lib/moonshine-homebrew/helper.rb recover
  EOS
end
