#!/usr/bin/env ruby
require_relative '../lib/release_catalog'
module MoonshineCask
  extend self
  ROOT = Pathname(__dir__).parent
  def render(recipe: nil, token: 'moonshine', tokens: nil, root: ROOT)
    recipe ||= MoonshineReleases.current(root)
    tokens ||= MoonshineReleases.tokens(root)
    raise 'Unknown generated cask token' unless tokens.include?(token)
    source = recipe.source
    release = recipe.release
    if recipe.template
      MoonshineReleases.validate_template(recipe.template, release, source)
      fields = MoonshineReleases.recipe_fields(release, source, recipe.scripts, recipe.template, approvals: recipe.approvals)
      MoonshineReleases.check(recipe.identity == MoonshineReleases.recipe_digest(fields), 'Frozen recipe identity differs')
      version = release['version']
      if token == 'moonshine@untested' || recipe.delivery&.fetch('style') == 'recipe'
        url = "https://github.com/hgaiser/moonshine/releases/download/v#{version}/#{release['filename']}"
        MoonshineReleases.check(recipe.template.include?("  url \"#{url}\"\n"), 'Untested recipe must pin its upstream URL independently')
        version = "#{version}+#{recipe.identity}"
      end
      text = recipe.template.gsub('__MOONSHINE_TOKEN__', token)
        .gsub('__MOONSHINE_VERSION__', version)
        .gsub('__MOONSHINE_CONFLICTS__', (tokens - [token]).map(&:inspect).join(', '))
      if token == 'moonshine@untested'
        text = text.sub("  caveats <<~EOS\n", "  caveats <<~EOS\n    Opt-in untested integration recipe. Package checks alone do not establish native acceptance.\n")
      end
      return text
    end
    guard = MoonshineReleases.read_file(Pathname(root)/'lib/moonshine_token_guard.rb', MoonshineReleases::MAX_SOURCE)
    guard_embedded = guard.lines.map { |line| line.strip.empty? ? "\n" : '    '+line }.join
    conflicts = (tokens - [token]).map(&:inspect).join(', ')
    embedded = source.lines.map { |line| line.strip.empty? ? "\n" : '    '+line }.join
    <<~CASK
      # Generated by tools/generate_cask.rb. Edit reviewed source inputs, then regenerate.
      # Unofficial integration. Not maintained or endorsed by Moonshine or Universal Blue.
      require "rbconfig"
      cask "#{token}" do
        version "#{release['version']}"
        sha256 "#{release['sha256']}"
        url "https://github.com/hgaiser/moonshine/releases/download/v\#{version}/#{release['filename']}"
        name "Moonshine (unofficial Homebrew integration)"
        desc "Streaming server with locally labeled Fedora Atomic host integration"
        homepage "https://github.com/hgaiser/moonshine"
        conflicts_with cask: [#{conflicts}]
        depends_on :linux
        depends_on arch: :x86_64
        depends_on formula: ["libarchive", "erofs-utils"]
        container type: :naked

        generated_script "moonshine-host.rb", content: <<~'MOONSHINE_RUBY'
      #{embedded}  MOONSHINE_RUBY

        generated_script "moonshine-token-guard.rb", content: <<~'MOONSHINE_GUARD'
      #{guard_embedded}  MOONSHINE_GUARD

        postflight_steps do
          run RbConfig.ruby,
              args: ["--disable=rubyopt", "{{staged_path}}/moonshine-token-guard.rb", "--brew",
                     "{{HOMEBREW_BREW_FILE}}", "--token", "evertonstz/moonshine-tap/#{token}"],
              print_stdout: true
          run RbConfig.ruby,
              args: ["--disable=rubyopt", "{{staged_path}}/moonshine-host.rb", "install", "--rpm",
                     "{{staged_path}}/#{release['filename']}",
                     "--bsdtar", "{{HOMEBREW_PREFIX}}/opt/libarchive/bin/bsdtar",
                     "--mkfs-erofs", "{{HOMEBREW_PREFIX}}/opt/erofs-utils/bin/mkfs.erofs",
                     "--fsck-erofs", "{{HOMEBREW_PREFIX}}/opt/erofs-utils/bin/fsck.erofs"],
              sudo: true,
              print_stdout: true
        end
        uninstall_preflight_steps do
          run RbConfig.ruby,
              args: ["--disable=rubyopt", "{{staged_path}}/moonshine-host.rb", "uninstall"],
              sudo: true,
              print_stdout: true
        end
        caveats <<~EOS
          Unofficial; not endorsed by Moonshine or Universal Blue.
          Experimental Fedora Atomic x86_64 integration, including Fedora-based UBlue images.
          Requires an OSTree-booted host; CentOS/RHEL derivatives and ARM are excluded.
          Only Bazzite has lifecycle acceptance; other eligible images are untested.
          Consult README.md for tested limits and version-switching instructions.
          Only one Moonshine cask variant can be installed. Ordinarily uninstall before switching tokens.
          Upgrades interrupt streaming. Ordinary uninstall removes owned active integration.
          Pairing/configuration, groups, lingering, administrator files and unrelated extensions remain.
          Inactive recovery material is retained in /var/lib/moonshine-homebrew.
          Fresh installation does not enable Moonshine or lingering.
          Reinstall can restore retained enabled/running choices.
          Explicit account activation: sudo systemctl enable --now moonshine@<user>.service
          Explicit cached recovery: sudo /var/lib/moonshine-homebrew/helper.rb recover
        EOS
      end
    CASK
  end
  def outputs(root: ROOT)
    recipes = MoonshineReleases.recipes(root)
    candidate = MoonshineCandidates.recipe(root)
    tokens = ['moonshine', *recipes.map { |recipe| MoonshineReleases.exact_token(recipe) }, *('moonshine@untested' if candidate)]
    tokens.to_h do |token|
      recipe = token == 'moonshine@untested' ? candidate : token == 'moonshine' ? recipes.first : recipes.find { |entry| token == MoonshineReleases.exact_token(entry) }
      ["Casks/#{token}.rb", render(recipe: recipe, token: token, tokens: tokens, root: root)]
    end
  end

  def generate(root: ROOT, check: false)
    root = Pathname(root)
    expected = outputs(root: root)
    existing = root.glob('Casks/moonshine*.rb').map { |path| path.relative_path_from(root).to_s }
    stale = existing - expected.keys
    if check
      raise 'Expired or extra generated Moonshine casks remain' unless stale.empty?
      expected.each do |name, text|
        path = root/name
        raise "Generated cask is stale: #{name}" unless path.file? && !path.symlink? && path.read == text
      end
    else
      expected.each do |name, text|
        path = root/name
        raise "Unsafe generated cask path: #{name}" if path.symlink?
        path.dirname.mkpath
        path.write(text)
      end
      stale.each do |name|
        path = root/name
        raise "Unsafe expired cask: #{name}" unless path.file? && !path.symlink?
        path.delete
      end
    end
    expected
  end

  def main(argv=ARGV)
    raise 'Usage: generate_cask.rb [--check]' unless argv.empty? || argv == ['--check']
    generate(check: argv == ['--check'])
    0
  rescue StandardError => e
    warn e.message
    1
  end
end
exit MoonshineCask.main if $PROGRAM_NAME == __FILE__
